### ISSUE TITLE
the hacks are good, but...

### ISSUE THREAD

**Issue by ghost** [asmyst17/Snake-mods#3]
there are a fue things. 1:
what dose the nuck thing do
2:
there are no new game modes. maby a gamemodes. ask me if you want ideas, or are thay to hard to make
3:
why is there a 12/11 one. what is so cool about it. tell me the purpose
4:
Can you make it where if you are not on the snake web page, it brangs you there then exacutes the script?

**Comment by ghost** [comment]
wate, how come in the code of it it seas DarkSnakeGang and grabs that, did you make it, or did you just steel the code!

**Comment by Vepcz0069** [comment]
i did not steal the code, i reuploaded it so more people could use it and
im working on my own snake mods

**Comment by ghost** [comment]
oh, thinks, but can you also answer the questions?

**Comment by Vepcz0069** [comment]
https://github.com/DarkSnakeGang/GoogleSnakeCustomMenuStuff/releases/tag/Permanent

im busy right now
